import Header from "@/block/header/header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import User from "@/img/headerSection/User.svg";
import Footer from "@/block/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header text="Sign Up" img={User} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
